### PR TITLE
Add UI for displaying light-statuses

### PR DESCRIPTION
**Pull request by billbogaiv**
UI is split into three-columns representing active TC-builds, Twitter feed, and TC pass/fail status.
Elements will scale based on viewport height and width (there may be some outliers where content breaks out of its container).
Updates to client are mostly done via socket-connection.
#### Original mockup

image
#### Proposed UI

image

### CODE REVIEW

**Comment by billbogaiv** [comment]
@khalidabuhakmeh I need feedback on adding margin to logo and increasing build font-size.

image

**Comment by billbogaiv** [comment]
@khalidabuhakmeh Do you think we still need the clock-graphic associated with build-time?

**Comment by billbogaiv** [comment]
Updated screenshot (includes TC and Twitter logos and more Twitter identifiers):

image

**Comment by khalidabuhakmeh** [comment]
:sparkles:

**Pull request merged**
